### ISSUE TITLE
Assertion in 1.9.2 throws JS error in 1.10.0

### ISSUE THREAD

**Issue by aarontam** [chaijs/chai#302]
We have several assertions in our core tests of the form

    expect(foo).to.exist.and.to.have.length(bar)

After upgrading to 1.10.0 from 1.9.2, these assertions now throw an error

    TypeError: '0' is not a function (evaluating 'expect(foo).to.exist.and.to.have.length(bar)')

I found that changing the assertion to

    expect(foo).to.exist().and.to.have.length(bar)

seems to fix the problem, but I'm not entirely sure why. Any insight would be appreciated, thanks!

**Comment by scottohara** [comment]
On Nov 11 2014, @lennym wrote..
> On further investigation, this seems to only be a problem for our in-browser tests run using karma, and not for unit tests run in a Node environment.

> Karma is running in Phantomjs@1.9.8, Chrome@36.0.1985 and Firefox@33.0.0. The failures and errors are the same in each case.

@lennym  - did you ever get this issue sorted?

I'm seeing a similar problem where `foo.should.have.been.calledWith(bar)` is throwing `undefined is not a function`.

My test suite used to work before upgrading to chai@1.10.0.
Curiously, I tried reverting back to chai@1.9.2 but I still get the same error.

At first, I thought it was only `calledWith()` that had the problem, because changing the test to `foo.should.have.been.called` passed;  but then I realised that `foo.should.not.have.been.called` also passed (which makes no sense...how can `should.have.been` and `should.not.have.been` both be passing?)

This occurs with both the should and expect APIs,  but not the assert API.  eg.

```
var foo = sinon.spy();
foo('bar');

// should
foo.should.have.been.called;  // PASS  (ok)
foo.should.not.have.been.called;  // PASS  (huh?)
foo.should.have.been.calledWith('bar');  // undefined is not a function

// expect
expect(foo).to.have.been.called; // PASS  (ok)
expect(foo).to.not.have.been.called; // PASS  (wat?)
expect(foo).to.have.been.calledWith('bar'); // undefined is not a function

// assert
assert.isTrue(foo.called);  // PASS  (ok)
assert.isFalse(foo.called);  // FAIL  (ok)
assert.isTrue(foo.calledWith('bar'));  // PASS (ok)
```

This behaviour was seen in karma in Chrome@41.0.2251.0, using the following npm modules:

```
$ npm ls --depth=0
├── chai@1.9.2
├── chai-as-promised@4.1.1
├── karma@0.12.30
├── karma-chai@0.1.0
├── karma-chrome-launcher@0.1.7
├── karma-mocha@0.1.10
├── karma-sinon@1.0.4
├── karma-sinon-chai@0.2.0
├── mocha@2.1.0
└── sinon@1.12.2
```

I checked if any of these modules bundled their own version of chai (perhaps one was still using 1.10.0 and ignoring my rolled-back 1.9.2 version?).  Only karma-sinon-chai does, but it seems to be using 1.9.2 as well:

```
├─┬ karma-sinon-chai@0.2.0
│ ├─┬ chai@1.9.2
│ │ ├── assertion-error@1.0.0
│ │ └─┬ deep-eql@0.1.3
│ │   └── type-detect@0.1.1
```

**Comment by joshperry** [comment]
@scottohara It looks to me like the sinon-chai assertions were not being registered with chai for some reason. This is a great example of some small issue causing assertion properties to produce false-positives because javascript silently ignores non-existent property accesses.

**Comment by keithamus** [comment]
Closing this - as we have a 2.0.0 tracking PR. 2.0.0 will revert the behaviour that is causing this issue. If anyone disagrees, feel free to comment and I'll re-open it.
