### ISSUE TITLE
Chai 1.9.2 does not work well with sinon-chai 2.5.0

### ISSUE THREAD

**Issue by mck-** [chaijs/chai#295]
`TypeError: 'undefined' is not a function` whenever `calledWith` is used.

Worked with 1.9.1
