### ISSUE TITLE
TypeError: Property 'undefined' of object #<Assertion> is not a function

### ISSUE THREAD

**Issue by brendanjerwin** [chaijs/chai#367]
Looks like, after upgrading to 2.0.0, I'm getting this when calling `expect(thing).not.to.be.undefined()`

Docs say:

> Can also be used as a function, which prevents some linter errors.
> 
> `expect(undefined).to.be.undefined();`

And, it seems to work as a property, but pisses off my linter. :)

**Comment by brendanjerwin** [comment]
Same with `exist()`.

**Comment by keithamus** [comment]
@brendanjerwin thanks for the issue.

The ability to use an assertion property as a function has been removed in 2.0.0. Unfortunately it is backwards incompatible the old style - using just the property - and was removed from Chai to keep the original behaviour from breaking.

The docs have yet to be updated - although should be very very soon. The PR for the docs is here: https://github.com/chaijs/chai-docs/pull/71.

If you want to keep calling the properties as functions, I recommend using the [dirty-chai](https://www.npmjs.com/package/dirty-chai) plugin, which will give you the behaviour you're after.

If we ever get notice the overwhelming majority of developers using chai want these assertion properties to only be functions - this behaviour may be changed. But this seems unlikely.

**Comment by keithamus** [comment]
@brendanjerwin just an FYI, http://chaijs.com/ now reflects the documentation for 2.0.0. See for example [.exist](http://chaijs.com/api/bdd/#-exist)
