### ISSUE TITLE
chai-spies broken in v5.1.0

### ISSUE THREAD

**Issue by iampava** [chaijs/chai#1610]
The following code fails when using:
* `chai`: 5.1.0
* `chai-spies`: 1.1.0

```
import * as chai from 'chai';
import chaiSpies from 'chai-spies';

chai.use(chaiSpies);
const expect = chai.expect;

function sum(a, b) {
    return a + b;
}

const spySum = chai.spy(sum);

expect(spySum).to.have.been.called.exactly(0);
```

The error is: `TypeError: chai.spy is not a function`

---

However, if I downgrade to `v4.3.10` and use CJS with the following code:

```
const chai = require('chai');
const chaiSpies = require('chai-spies');

chai.use(chaiSpies);
const expect = chai.expect;

function sum(a, b) {
    return a + b;
}

const spySum = chai.spy(sum);

expect(spySum).to.have.been.called.exactly(0);
```

It works.

**Comment by 43081j** [comment]
this is most likely caused by #1569 

you can do:

```ts
import * as chaiModule from 'chai';

const chai = chaiModule.use(chaiSpies);
```

**Comment by 43081j** [comment]
closing since the following usage works:

```ts
import * as chaiModule from 'chai';
import chaiSpies from 'chai-spies';

const chai = chaiModule.use(chaiSpies);
const expect = chai.expect;

function sum(a, b) {
    return a + b;
}

const spySum = chai.spy(sum);

expect(spySum).to.have.been.called.exactly(0);
```
